# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  print_pipeline_id:
    parameters:
      string_to_print:
        type: string
    steps:
      - run: echo << parameters.string_to_print >>

  error_handler:
    steps:
      - run:
          command: echo ERROR OCCURED!!!!!!
          when: on_fail

# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: npm run test

  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: npm audit

      - error_handler


# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - build
      - test:
          requires: [build]
      - analyze:
          requires: [test]

