# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

#working_directory: ~/react-slingshot/
steps:
  - checkout

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: npm run test

  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: npm audit


# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - build
      - test:
          requires: [build]
      - analyze:
          requires: [test]

